name: smart_lock
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  get_storage: ^2.0.3

  firebase_database: ^8.1.0
  
  google_fonts: ^2.1.0
  simple_animations: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: CustomIcons # the name of your font family
      fonts:
        - asset: assets/CustomIcons.ttf # your font file name and the directory